"""
Cross-Repo Linker test.

Registers the three fixture repos generated by setup_cross_repo_fixtures.py
(purging any prior registration by the same name first, so this is safe to
re-run), runs CrossRepoLinker.link(), and prints the resulting edges
grouped by confidence so you can check all three strategies fired:

  - orders-service <- checkout-service        : expect CONFIRMED (spec match)
  - notifications-service <- checkout-service : expect INFERRED (name match, no spec)
  - orders-service <-> notifications-service  : expect CONFIRMED (manual override)

Usage:
    python test_cross_repo.py [fixtures_dir]
"""
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
import sys

from ingestion.repo_registry import RepoRegistry
from ingestion.cross_repo_linker import CrossRepoLinker
from db.connection import connection

FIXTURES_DIR = sys.argv[1] if len(sys.argv) > 1 else "./cross_repo_fixtures"
FIXTURE_REPO_NAMES = ["orders-service", "checkout-service", "notifications-service"]


from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def node_label(node_id: str) -> str:
    with connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT r.name, gn.qualified_name FROM graph_nodes gn
                JOIN repos r ON gn.repo_id = r.id
                WHERE gn.id = %s
                """,
                (node_id,),
            )
            row = cur.fetchone()
    return f"{row[0]}:{row[1]}" if row else f"<unknown:{node_id}>"


def main():
    registry = RepoRegistry()

    for repo_name in FIXTURE_REPO_NAMES:
        local_path = os.path.abspath(os.path.join(FIXTURES_DIR, repo_name))
        if not os.path.isdir(local_path):
            print(f"Fixture not found at {local_path} — run "
                  f"setup_cross_repo_fixtures.py first.")
            sys.exit(1)

        existing = registry.get_repo_by_name(repo_name)
        if existing is not None:
            print(f"{repo_name} already registered — purging for a clean re-test...")
            registry.purge(existing.id)

        print(f"Registering {repo_name} from {local_path}...")
        registry.register(name=repo_name, git_url=local_path, default_branch="main")

    print("\nRunning CrossRepoLinker...")
    linker = CrossRepoLinker()
    edges = linker.link()

    print(f"\n=== {len(edges)} cross-repo edges found ===\n")
    by_confidence: dict[str, list] = {"confirmed": [], "inferred": []}
    for edge in edges:
        by_confidence.setdefault(edge.confidence, []).append(edge)

    for confidence in ("confirmed", "inferred"):
        print(f"--- {confidence.upper()} ({len(by_confidence[confidence])}) ---")
        for edge in by_confidence[confidence]:
            source_label = node_label(edge.source_node_id)
            target_label = node_label(edge.target_node_id)
            print(f"  [{edge.edge_type}] {source_label}  -->  {target_label}")
        print()


if __name__ == "__main__":
    main()